# Generated by Django 4.1.5 on 2023-02-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_category_product_remove_questions_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(upload_to='D:\\Programming\\Python\\ПРОЕКТ\\pet_shop\\images\\1.jpeg'),
        ),
    ]
