# Generated by Django 4.1.5 on 2023-02-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_category_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(upload_to='D:\\Programming\\Python\\ПРОЕКТ\\pet_shop\\images\\'),
        ),
    ]
