# Generated by Django 4.1.5 on 2023-02-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_category_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='изображение'),
        ),
    ]
