# Generated by Django 4.1.5 on 2023-02-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_category_category_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=128, verbose_name='ФИО')),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
            ],
        ),
    ]
