# Generated by Django 4.1.5 on 2023-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.AlterField(
            model_name='order',
            name='FIO',
            field=models.CharField(max_length=128),
        ),
    ]
