# Generated by Django 4.1.5 on 2023-03-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_rename_product_products_alter_order_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='products',
            name='silka',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
