# Generated by Django 4.1.5 on 2023-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_products_price_products_silka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='silka',
        ),
        migrations.AddField(
            model_name='products',
            name='access',
            field=models.CharField(default='none', max_length=128, verbose_name='Аксессуар'),
        ),
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
